### ISSUE TITLE
@Sahil-Gupta584 Thanks for considering my query and the new update.

### ISSUE THREAD

**Issue by merbin2012** [Sahil-Gupta584/video-downloader#2]
@Sahil-Gupta584 Thanks for considering my query and the new update.
But this issue is still found, please check the below-attached image.

    import s from 'videos-downloader';

![1](https://github.com/user-attachments/assets/daba943a-e1fa-4797-aa14-9c9de93932fe)
![2](https://github.com/user-attachments/assets/0d615328-984a-4f46-9a5a-3daeab4e0acf)

_Originally posted by @merbin2012 in https://github.com/Sahil-Gupta584/video-downloader/issues/1#issuecomment-2276388696_

**Comment by Sahil-Gupta584** [comment]
@merbin2012 thank you for reopening this issue i have updated code again and teste all methods and now i thing all vulnerabilities has been resolved so please check and response me with the lates version 1.0.4
